### ISSUE TITLE
Use Project

### ISSUE THREAD

**Issue by nabinabila** [Valentyn1997/xray#2]
I wanna use the project, how could i run it and have models results (the visualization and evaluation metrics) ?

**Comment by Valentyn1997** [comment]
> I wanna use the project, how could i run it and have models results (the visualization and evaluation metrics) ?

In the most basic setting, you would need to:
1. Install all the libraries, listed in `requirements.txt`.
2. Download MURA dataset and put it to `data/train` folder, in the project root directory.
3. Start MlFlow server.
4. Run `train.py` (https://github.com/Valentyn1997/xray/blob/master/src/models/train.py) and monitor models on MlFlow server.
5. Use saved models for visualisations (see notebooks https://github.com/Valentyn1997/xray/tree/master/notebooks/models) and evaluation (see notebook https://github.com/Valentyn1997/xray/blob/master/notebooks/Experiments_comparison.ipynb)

There are also some scripts for data preprocessing in https://github.com/Valentyn1997/xray/tree/master/src/features (e.g. cropping and hand-detection).

**Comment by viettr** [comment]
Regarding point 4: You need to specify the model in line 27. Currently you can choose between: AlphaGan, BottleneckAutoencoder, BaselineAutoencoder, DCGAN, SAGAN and VAE.

**Comment by Valentyn1997** [comment]
Do you mean, you need specific model weights? Unfortunately, we don't anymore store the weights of the models, reported in the paper.

**Comment by viettr** [comment]
I mean one needs to specify the model one wants to train in the line 27 in the train.py file.
