### ISSUE TITLE
Training the data

### ISSUE THREAD

**Issue by rafael-alencar29** [Valentyn1997/xray#3]
I'm trying to run the project I came across a big issue. It's taking to long to train the models, and I'm running "train.py" on google Colab, which has limited resources when comes to time. So, how can I decrease the number of
"epochs"? Should I decrease the amount of data?

By decreasing the number of epochs I believe I can reduce the training time.

**Comment by DianaDI** [comment]
Hello! If you look at the code in train.py, you will easily see that parameters like the number of epochs can be modified in the https://github.com/Valentyn1997/xray/blob/master/src/models/run_params.py. 

You can decrease the amount of data to reduce training time, but that can affect the quality of the trained model.

**Comment by rafael-alencar29** [comment]
thanks!
