### ISSUE TITLE
about dataset?

### ISSUE THREAD

**Issue by caodoanh2001** [Valentyn1997/xray#5]
Hi,

Thank you for great work. But it seems that your tutorial of downloading dataset is so unclear.
So, can you describe clearly how we work with `data.dvc` more clearer?

Best regards, and Happy Lunar New Year.

**Comment by Valentyn1997** [comment]
Hey! 

Sorry for such a delayed response! 

MURA dataset should be downloaded manually (from https://stanfordmlgroup.github.io/competitions/mura/). Unfortunately, we cannot provide the processed version of the MURA dataset, as it is not allowed under the user agreement.

Nevertheless, you could perform offline pre-processing steps on your own with our code: 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/23198776/167673709-d148d589-6692-4abe-b587-9c3712ff1c9a.png">

1. Cropping -> `xray/src/features/crop/square-crop.py`
2. Hand center localisation -> `xray/src/features/hand_detection/detect_and_save_hands.py`
3. Hand Segmentation -> Was done in image processing software, e.g., PhotoShop batch processing (around 10 hours of work).

P.S. The usage of DVC is optional: it was used to share data internally.

I hope, this could help you.
